ALTER TABLE "Product" ALTER COLUMN "price" TYPE DECIMAL(10, 2) USING "price"::DECIMAL(10, 2);
ALTER TABLE "Order" ALTER COLUMN "total" TYPE DECIMAL(10, 2) USING "total"::DECIMAL(10, 2);
ALTER TABLE "OrderItem" ALTER COLUMN "productPrice" TYPE DECIMAL(10, 2) USING "productPrice"::DECIMAL(10, 2);
