const ORDER_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
};

const ORDER_STATUS_LIST = Object.values(ORDER_STATUS);

module.exports = { ORDER_STATUS, ORDER_STATUS_LIST };